export const CONTENT_TYPES = {
  blog: {
    id: 'blog',
    label: 'Blog Posts',
    icon: 'FileText',
    primary: 'gemini',
    fallbacks: ['llama', 'grok'],
    color: '#4285F4',
    description: 'Long-form SEO-optimized articles',
    monthlyTarget: 8,
  },
  email: {
    id: 'email',
    label: 'Email Sequences',
    icon: 'Mail',
    primary: 'grok',
    fallbacks: ['gemini', 'mistral'],
    color: '#FF6B35',
    description: 'Nurture & campaign emails',
    monthlyTarget: 12,
  },
  social: {
    id: 'social',
    label: 'Social Media',
    icon: 'Share2',
    primary: 'mistral',
    fallbacks: ['grok', 'gemini'],
    color: '#7C3AED',
    description: 'Platform-native social posts',
    monthlyTarget: 30,
  },
  ad: {
    id: 'ad',
    label: 'Ad Copy',
    icon: 'Megaphone',
    primary: 'grok',
    fallbacks: ['mistral', 'gemini'],
    color: '#DC2626',
    description: 'Conversion-focused ad creative',
    monthlyTarget: 20,
  },
  landing: {
    id: 'landing',
    label: 'Landing Pages',
    icon: 'Layout',
    primary: 'gemini',
    fallbacks: ['grok', 'llama'],
    color: '#D97706',
    description: 'High-converting page copy',
    monthlyTarget: 4,
  },
  casestudy: {
    id: 'casestudy',
    label: 'Case Studies',
    icon: 'BookOpen',
    primary: 'llama',
    fallbacks: ['gemini', 'grok'],
    color: '#059669',
    description: 'Client success narratives',
    monthlyTarget: 2,
  },
};

export const CONTENT_TYPE_IDS = Object.keys(CONTENT_TYPES);